--- #YAML:1.0
name:                Mail-Maps-Lookup
version:             0.02
abstract:            Query the MAPS lookup service via DNS
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Net::DNS:                      0.29
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Matteo Cantoni <matteo.cantoni@nothink.org>
